#!/usr/bin/env python3
"""
Coverage tests for scripts/mg_sign.py -- targeting low-coverage CLI commands
and core signing/verification functions.

Generated by TASK-015 to boost overall coverage toward 60%.
"""

import hashlib
import json
import sys
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from scripts.mg_sign import (  # noqa: E402
    generate_key,
    load_key,
    sign_bundle,
    verify_bundle_signature,
    _compute_signature,
    _detect_algorithm,
)


class TestGenerateKey:
    """Tests for HMAC key generation."""

    def test_generate_key_returns_dict(self):
        key = generate_key()
        assert isinstance(key, dict)
        assert "version" in key
        assert key["version"] == "hmac-sha256-v1"

    def test_generate_key_has_key_hex_and_fingerprint(self):
        key = generate_key()
        assert "key_hex" in key
        assert "fingerprint" in key
        assert len(key["key_hex"]) == 64  # 32 bytes hex
        assert len(key["fingerprint"]) == 64  # SHA-256 hex

    def test_generate_key_unique(self):
        k1 = generate_key()
        k2 = generate_key()
        assert k1["key_hex"] != k2["key_hex"]

    def test_generate_key_fingerprint_matches(self):
        key = generate_key()
        expected_fp = hashlib.sha256(bytes.fromhex(key["key_hex"])).hexdigest()
        assert key["fingerprint"] == expected_fp


class TestDetectAlgorithm:
    """Tests for algorithm detection from key data."""

    def test_detect_hmac(self):
        key = generate_key()
        assert _detect_algorithm(key) == "hmac"

    def test_detect_ed25519(self):
        key = {"version": "ed25519-v1", "public_key_hex": "ab" * 32}
        assert _detect_algorithm(key) == "ed25519"

    def test_detect_unknown_raises(self):
        key = {"version": "unknown-v99"}
        with pytest.raises(ValueError, match="Unknown key version"):
            _detect_algorithm(key)

    def test_detect_missing_version_raises(self):
        key = {"key": "deadbeef"}
        with pytest.raises(ValueError, match="Unknown key version"):
            _detect_algorithm(key)


class TestComputeSignature:
    """Tests for HMAC signature computation."""

    def test_hmac_signature_deterministic(self):
        sig1 = _compute_signature("abc123", "deadbeef" * 8)
        sig2 = _compute_signature("abc123", "deadbeef" * 8)
        assert sig1 == sig2

    def test_hmac_signature_different_inputs(self):
        sig1 = _compute_signature("abc123", "deadbeef" * 8)
        sig2 = _compute_signature("xyz789", "deadbeef" * 8)
        assert sig1 != sig2

    def test_hmac_signature_is_hex(self):
        sig = _compute_signature("test", "aa" * 32)
        assert len(sig) == 64
        int(sig, 16)  # must be valid hex


class TestLoadKey:
    """Tests for key loading from file."""

    def test_load_key_valid_hmac(self, tmp_path):
        key = generate_key()
        key_path = tmp_path / "test_key.json"
        key_path.write_text(json.dumps(key), encoding="utf-8")
        loaded = load_key(key_path)
        assert loaded["version"] == key["version"]
        assert loaded["key_hex"] == key["key_hex"]

    def test_load_key_missing_file(self, tmp_path):
        key_path = tmp_path / "nonexistent.json"
        with pytest.raises((ValueError, FileNotFoundError)):
            load_key(key_path)

    def test_load_key_invalid_json(self, tmp_path):
        key_path = tmp_path / "bad.json"
        key_path.write_text("not json", encoding="utf-8")
        with pytest.raises(ValueError):
            load_key(key_path)

    def test_load_key_missing_key_hex(self, tmp_path):
        key_path = tmp_path / "incomplete.json"
        key_path.write_text(json.dumps({"version": "hmac-sha256-v1"}), encoding="utf-8")
        with pytest.raises(ValueError, match="missing 'key_hex'"):
            load_key(key_path)


class TestSignAndVerifyBundle:
    """Integration tests for sign + verify round-trip."""

    def _make_minimal_bundle(self, tmp_path):
        bundle = tmp_path / "bundle"
        bundle.mkdir(parents=True, exist_ok=True)

        evidence = {"claim": "TEST-01", "result": "PASS"}
        evidence_file = bundle / "evidence.json"
        evidence_file.write_text(json.dumps(evidence), encoding="utf-8")

        sha = hashlib.sha256(evidence_file.read_bytes()).hexdigest()
        files = [{"relpath": "evidence.json", "sha256": sha,
                  "bytes": evidence_file.stat().st_size}]
        lines_str = "\n".join(
            f"{e['relpath']}:{e['sha256']}"
            for e in sorted(files, key=lambda x: x["relpath"])
        )
        root_hash = hashlib.sha256(lines_str.encode("utf-8")).hexdigest()
        manifest = {"version": "v1", "files": files, "root_hash": root_hash}
        (bundle / "pack_manifest.json").write_text(
            json.dumps(manifest, indent=2), encoding="utf-8")
        return bundle, root_hash

    def test_sign_and_verify_roundtrip(self, tmp_path):
        bundle, root_hash = self._make_minimal_bundle(tmp_path)
        key = generate_key()
        key_path = tmp_path / "key.json"
        key_path.write_text(json.dumps(key), encoding="utf-8")

        sig_result = sign_bundle(bundle, key_path)
        assert sig_result is not None
        assert "signature" in sig_result
        assert "signed_root_hash" in sig_result

        sig_file = bundle / "bundle_signature.json"
        assert sig_file.exists(), "sign_bundle should create bundle_signature.json"

        ok, msg = verify_bundle_signature(bundle, key_path)
        assert ok is True, f"Valid signature should verify: {msg}"

    def test_verify_tampered_manifest_root_hash(self, tmp_path):
        """Tamper with manifest root_hash after signing -- signature check catches it."""
        bundle, root_hash = self._make_minimal_bundle(tmp_path)
        key = generate_key()
        key_path = tmp_path / "key.json"
        key_path.write_text(json.dumps(key), encoding="utf-8")

        sign_bundle(bundle, key_path)

        # Tamper: change root_hash in manifest (simulates file modification + manifest rebuild)
        manifest_path = bundle / "pack_manifest.json"
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest["root_hash"] = "0" * 64
        manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

        ok, msg = verify_bundle_signature(bundle, key_path)
        assert ok is False, f"Tampered root_hash should fail verification: {msg}"
        assert "modified after signing" in msg

    def test_verify_wrong_key(self, tmp_path):
        bundle, root_hash = self._make_minimal_bundle(tmp_path)
        key1 = generate_key()
        key2 = generate_key()
        key1_path = tmp_path / "key1.json"
        key2_path = tmp_path / "key2.json"
        key1_path.write_text(json.dumps(key1), encoding="utf-8")
        key2_path.write_text(json.dumps(key2), encoding="utf-8")

        sign_bundle(bundle, key1_path)
        ok, msg = verify_bundle_signature(bundle, key2_path)
        assert ok is False, f"Wrong key should fail verification: {msg}"

    def test_verify_no_key_presence_check(self, tmp_path):
        """Verify without key -- should do presence check only."""
        bundle, root_hash = self._make_minimal_bundle(tmp_path)
        key = generate_key()
        key_path = tmp_path / "key.json"
        key_path.write_text(json.dumps(key), encoding="utf-8")

        sign_bundle(bundle, key_path)
        ok, msg = verify_bundle_signature(bundle)  # no key
        assert ok is True
        assert "SIGNATURE PRESENT" in msg

    def test_verify_missing_signature_file(self, tmp_path):
        bundle, root_hash = self._make_minimal_bundle(tmp_path)
        ok, msg = verify_bundle_signature(bundle)
        assert ok is False
        assert "missing" in msg.lower()

    def test_sign_missing_manifest(self, tmp_path):
        bundle = tmp_path / "empty_bundle"
        bundle.mkdir()
        key = generate_key()
        key_path = tmp_path / "key.json"
        key_path.write_text(json.dumps(key), encoding="utf-8")
        with pytest.raises(FileNotFoundError):
            sign_bundle(bundle, key_path)
