#!/usr/bin/env python3
"""
Coverage tests for scripts/mg_temporal.py -- targeting create_temporal_commitment,
verify_temporal_commitment, and write_temporal_commitment.

Generated by TASK-015 to boost overall coverage toward 60%.
"""

import hashlib
import json
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from scripts.mg_temporal import (  # noqa: E402
    create_temporal_commitment,
    verify_temporal_commitment,
    write_temporal_commitment,
    TEMPORAL_FILE,
)


_MOCK_BEACON = {
    "outputValue": "abcdef01" * 16,
    "timeStamp": "2026-03-19T14:00:00Z",
    "uri": "https://beacon.nist.gov/beacon/2.0/chain/test/pulse/42",
}


class TestCreateTemporalCommitment:
    """Tests for temporal commitment creation."""

    def test_create_returns_dict(self):
        with patch("scripts.mg_temporal._fetch_beacon_pulse", return_value=_MOCK_BEACON):
            tc = create_temporal_commitment("deadbeef" * 8)
        assert isinstance(tc, dict)
        assert "pre_commitment_hash" in tc
        assert "beacon_output_value" in tc
        assert "beacon_timestamp" in tc
        assert "temporal_binding" in tc

    def test_create_uses_root_hash(self):
        rh1 = "a" * 64
        rh2 = "b" * 64
        with patch("scripts.mg_temporal._fetch_beacon_pulse", return_value=_MOCK_BEACON):
            tc1 = create_temporal_commitment(rh1)
            tc2 = create_temporal_commitment(rh2)
        assert tc1["pre_commitment_hash"] != tc2["pre_commitment_hash"]

    def test_create_deterministic_same_inputs(self):
        rh = "c" * 64
        with patch("scripts.mg_temporal._fetch_beacon_pulse", return_value=_MOCK_BEACON):
            tc1 = create_temporal_commitment(rh)
            tc2 = create_temporal_commitment(rh)
        assert tc1["temporal_binding"] == tc2["temporal_binding"]

    def test_create_temporal_binding_is_sha256(self):
        with patch("scripts.mg_temporal._fetch_beacon_pulse", return_value=_MOCK_BEACON):
            tc = create_temporal_commitment("f" * 64)
        assert len(tc["temporal_binding"]) == 64
        int(tc["temporal_binding"], 16)  # must be valid hex


class TestWriteTemporalCommitment:
    """Tests for writing temporal commitment to bundle."""

    def test_write_creates_file(self, tmp_path):
        bundle = tmp_path / "bundle"
        bundle.mkdir()
        with patch("scripts.mg_temporal._fetch_beacon_pulse", return_value=_MOCK_BEACON):
            tc = create_temporal_commitment("e" * 64)
        result = write_temporal_commitment(bundle, tc)
        assert (bundle / TEMPORAL_FILE).exists()

    def test_write_content_matches(self, tmp_path):
        bundle = tmp_path / "bundle"
        bundle.mkdir()
        with patch("scripts.mg_temporal._fetch_beacon_pulse", return_value=_MOCK_BEACON):
            tc = create_temporal_commitment("d" * 64)
        write_temporal_commitment(bundle, tc)
        written = json.loads((bundle / TEMPORAL_FILE).read_text(encoding="utf-8"))
        assert written["temporal_binding"] == tc["temporal_binding"]


class TestVerifyTemporalCommitment:
    """Tests for temporal commitment verification."""

    def _make_bundle_with_temporal(self, tmp_path, root_hash=None):
        bundle = tmp_path / "bundle"
        bundle.mkdir(parents=True, exist_ok=True)

        evidence = {"claim": "COVERAGE-TEST", "result": "PASS"}
        ev_file = bundle / "evidence.json"
        ev_file.write_text(json.dumps(evidence), encoding="utf-8")

        sha = hashlib.sha256(ev_file.read_bytes()).hexdigest()
        files = [{"relpath": "evidence.json", "sha256": sha,
                  "bytes": ev_file.stat().st_size}]
        lines_str = "\n".join(
            f"{e['relpath']}:{e['sha256']}"
            for e in sorted(files, key=lambda x: x["relpath"])
        )
        rh = hashlib.sha256(lines_str.encode("utf-8")).hexdigest()
        manifest = {"version": "v1", "files": files, "root_hash": rh}
        (bundle / "pack_manifest.json").write_text(
            json.dumps(manifest, indent=2), encoding="utf-8")

        with patch("scripts.mg_temporal._fetch_beacon_pulse", return_value=_MOCK_BEACON):
            tc = create_temporal_commitment(rh)
        write_temporal_commitment(bundle, tc)
        return bundle, tc, rh

    def test_verify_valid_commitment(self, tmp_path):
        bundle, tc, rh = self._make_bundle_with_temporal(tmp_path)
        ok, msg = verify_temporal_commitment(bundle)
        assert ok is True, f"Valid temporal commitment should verify: {msg}"

    def test_verify_missing_file(self, tmp_path):
        bundle = tmp_path / "bundle"
        bundle.mkdir()
        (bundle / "pack_manifest.json").write_text(
            json.dumps({"version": "v1", "files": [], "root_hash": "0" * 64}),
            encoding="utf-8")
        ok, msg = verify_temporal_commitment(bundle)
        # Layer 5 is optional -- missing temporal file means skipped, not failed
        assert ok is True, f"Missing temporal file should skip (not fail): {msg}"
        assert "skipped" in msg.lower() or "no temporal" in msg.lower()

    def test_verify_corrupted_binding(self, tmp_path):
        bundle, tc, rh = self._make_bundle_with_temporal(tmp_path)
        tc_path = bundle / TEMPORAL_FILE
        data = json.loads(tc_path.read_text(encoding="utf-8"))
        data["temporal_binding"] = "0" * 64
        tc_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        ok, msg = verify_temporal_commitment(bundle)
        assert ok is False, f"Corrupted binding should fail: {msg}"

    def test_verify_modified_beacon(self, tmp_path):
        bundle, tc, rh = self._make_bundle_with_temporal(tmp_path)
        tc_path = bundle / TEMPORAL_FILE
        data = json.loads(tc_path.read_text(encoding="utf-8"))
        data["beacon_output_value"] = "ff" * 32
        tc_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        ok, msg = verify_temporal_commitment(bundle)
        assert ok is False, f"Modified beacon should fail: {msg}"
